cipher: chachapoly
firewall:
  conntrack:
    default_timeout: 10m
    max_connections: 30000
    tcp_timeout: 12m
    udp_timeout: 3m
  inbound:
  - host: nest_service
    port: 53535
    proto: tcp
  outbound:
  - host: nest_service
    port: any
    proto: tcp
lighthouse:
  am_lighthouse: false
  interval: 60
listen:
  host: '0.0.0.0'
  port: 4242
logging:
  format: text
  level: info
pki:
  ca: /home/nest_ca/mnt/config/nebula/nest_system_ca.crt
  cert: /home/nest_ca/mnt/config/nebula/nest_ca.crt
  key: /home/nest_ca/mnt/config/nebula/nest_ca.key
punchy:
  punch: true
  respond: true
relay:
  am_relay: false
  use_relays: false
static_host_map:
  - '192.168.80.1': ["nest_ca:4242"]
tun:
  dev: nebula
  disabled: false
  drop_local_broadcast: false
  drop_multicast: false
  mtu: 1300
  tx_queue: 500
